1. Importing Libraries

In [47]:
import pandas as pd
import numpy as np

2. Importing dataset

In [48]:
df = pd.read_csv("/content/buddymove_holidayiq.csv")
df

      User Id  Sports  Religious  Nature  Theatre  Shopping  Picnic
0      User 1       2         77      79       69        68      95
1      User 2       2         62      76       76        69      68
2      User 3       2         50      97       87        50      75
3      User 4       2         68      77       95        76      61
4      User 5       2         98      54       59        95      86
..        ...     ...        ...     ...      ...       ...     ...
244  User 245      18        139     148      129       129     168
245  User 246      22        114     228      104        84     168
246  User 247      20        124     178      104       158     174
247  User 248      20        133     149      139       144     213
248  User 249      20        143     149      139       159     143

[249 rows x 7 columns]

3. Taking care of missing data

*a) isnull()/ notnull()-  Both function help in checking whether a value is NaN or not.*

In [49]:
df.isnull()

     User Id  Sports  Religious  Nature  Theatre  Shopping  Picnic
0      False   False      False   False    False     False   False
1      False   False      False   False    False     False   False
2      False   False      False   False    False     False   False
3      False   False      False   False    False     False   False
4      False   False      False   False    False     False   False
..       ...     ...        ...     ...      ...       ...     ...
244    False   False      False   False    False     False   False
245    False   False      False   False    False     False   False
246    False   False      False   False    False     False   False
247    False   False      False   False    False     False   False
248    False   False      False   False    False     False   False

[249 rows x 7 columns]

In [50]:
print(df.isnull().sum())

User Id      0
Sports       0
Religious    0
Nature       0
Theatre      0
Shopping     0
Picnic       0
dtype: int64

*As there are no missing values we will change some values to NAN for the purpose of demonstration*

In [51]:
df=df.replace(59,np.NaN)
df=df.replace(76,np.NaN)
df
print(df.isnull().sum())

User Id      0
Sports       0
Religious    4
Nature       6
Theatre      4
Shopping     5
Picnic       2
dtype: int64

In [52]:
df.isnull()

     User Id  Sports  Religious  Nature  Theatre  Shopping  Picnic
0      False   False      False   False    False     False   False
1      False   False      False    True     True     False   False
2      False   False      False   False    False     False   False
3      False   False      False   False    False      True   False
4      False   False      False   False     True     False   False
..       ...     ...        ...     ...      ...       ...     ...
244    False   False      False   False    False     False   False
245    False   False      False   False    False     False   False
246    False   False      False   False    False     False   False
247    False   False      False   False    False     False   False
248    False   False      False   False    False     False   False

[249 rows x 7 columns]

In [53]:
bool_series = pd.notnull(df)
bool_series

     User Id  Sports  Religious  Nature  Theatre  Shopping  Picnic
0       True    True       True    True     True      True    True
1       True    True       True   False    False      True    True
2       True    True       True    True     True      True    True
3       True    True       True    True     True     False    True
4       True    True       True    True    False      True    True
..       ...     ...        ...     ...      ...       ...     ...
244     True    True       True    True     True      True    True
245     True    True       True    True     True      True    True
246     True    True       True    True     True      True    True
247     True    True       True    True     True      True    True
248     True    True       True    True     True      True    True

[249 rows x 7 columns]

Filling missing values using fillna(), replace() and interpolate()
In order to fill null values in a datasets, we use fillna(), replace() and interpolate() function these function replace NaN values with some value of their own.

Filling null values with a single value

In [68]:
df.fillna(0)

      User Id  Sports  Religious  Nature  Theatre  Shopping  Picnic
0      User 1       2       77.0    79.0     69.0      68.0    95.0
1      User 2       2       62.0     0.0      0.0      69.0    68.0
2      User 3       2       50.0    97.0     87.0      50.0    75.0
3      User 4       2       68.0    77.0     95.0       0.0    61.0
4      User 5       2       98.0    54.0      0.0      95.0    86.0
..        ...     ...        ...     ...      ...       ...     ...
244  User 245      18      139.0   148.0    129.0     129.0   168.0
245  User 246      22      114.0   228.0    104.0      84.0   168.0
246  User 247      20      124.0   178.0    104.0     158.0   174.0
247  User 248      20      133.0   149.0    139.0     144.0   213.0
248  User 249      20      143.0   149.0    139.0     159.0   143.0

[249 rows x 7 columns]

Filling null values with the previous ones

In [69]:
df.fillna(method ='pad')

      User Id  Sports  Religious  Nature  Theatre  Shopping  Picnic
0      User 1       2       77.0    79.0     69.0      68.0    95.0
1      User 2       2       62.0    79.0     69.0      69.0    68.0
2      User 3       2       50.0    97.0     87.0      50.0    75.0
3      User 4       2       68.0    77.0     95.0      50.0    61.0
4      User 5       2       98.0    54.0     95.0      95.0    86.0
..        ...     ...        ...     ...      ...       ...     ...
244  User 245      18      139.0   148.0    129.0     129.0   168.0
245  User 246      22      114.0   228.0    104.0      84.0   168.0
246  User 247      20      124.0   178.0    104.0     158.0   174.0
247  User 248      20      133.0   149.0    139.0     144.0   213.0
248  User 249      20      143.0   149.0    139.0     159.0   143.0

[249 rows x 7 columns]

Filling null value with the next ones

In [70]:
df.fillna(method ='bfill')

      User Id  Sports  Religious  Nature  Theatre  Shopping  Picnic
0      User 1       2       77.0    79.0     69.0      68.0    95.0
1      User 2       2       62.0    97.0     87.0      69.0    68.0
2      User 3       2       50.0    97.0     87.0      50.0    75.0
3      User 4       2       68.0    77.0     95.0      95.0    61.0
4      User 5       2       98.0    54.0     93.0      95.0    86.0
..        ...     ...        ...     ...      ...       ...     ...
244  User 245      18      139.0   148.0    129.0     129.0   168.0
245  User 246      22      114.0   228.0    104.0      84.0   168.0
246  User 247      20      124.0   178.0    104.0     158.0   174.0
247  User 248      20      133.0   149.0    139.0     144.0   213.0
248  User 249      20      143.0   149.0    139.0     159.0   143.0

[249 rows x 7 columns]

In [71]:
df["Theatre"].fillna("Not present", inplace = True)
df

      User Id  Sports  Religious  Nature      Theatre  Shopping  Picnic
0      User 1       2       77.0    79.0         69.0      68.0    95.0
1      User 2       2       62.0     NaN  Not present      69.0    68.0
2      User 3       2       50.0    97.0         87.0      50.0    75.0
3      User 4       2       68.0    77.0         95.0       NaN    61.0
4      User 5       2       98.0    54.0  Not present      95.0    86.0
..        ...     ...        ...     ...          ...       ...     ...
244  User 245      18      139.0   148.0        129.0     129.0   168.0
245  User 246      22      114.0   228.0        104.0      84.0   168.0
246  User 247      20      124.0   178.0        104.0     158.0   174.0
247  User 248      20      133.0   149.0        139.0     144.0   213.0
248  User 249      20      143.0   149.0        139.0     159.0   143.0

[249 rows x 7 columns]

Filling a null values using replace() method

In [72]:
df[10:25]

    User Id  Sports  Religious  Nature Theatre  Shopping  Picnic
10  User 11       3      107.0    54.0    64.0     103.0    94.0
11  User 12       3      103.0    60.0    63.0     102.0    93.0
12  User 13       3       64.0    82.0    82.0      75.0    69.0
13  User 14       3       93.0    54.0    74.0     103.0    69.0
14  User 15       3       63.0    82.0    81.0      78.0    69.0
15  User 16       3       82.0    79.0    75.0      75.0    82.0
16  User 17       5        NaN   131.0   103.0      54.0    86.0
17  User 18       5       56.0   124.0   108.0      56.0    85.0
18  User 19       4       85.0    67.0   111.0      65.0    72.0
19  User 20       5      114.0    83.0    65.0     114.0   102.0
20  User 21       4       93.0    82.0    79.0      79.0    90.0
21  User 22       4      105.0    52.0    75.0     113.0    78.0
22  User 23       5       69.0   118.0    74.0      66.0   101.0
23  User 24       4       71.0   123.0    64.0       NaN   102.0
24  User 25       5       88.0    94.0    81.0      79.0    91.0

In [73]:
df.replace(to_replace = np.nan, value = -99)

      User Id  Sports  Religious  Nature      Theatre  Shopping  Picnic
0      User 1       2       77.0    79.0         69.0      68.0    95.0
1      User 2       2       62.0   -99.0  Not present      69.0    68.0
2      User 3       2       50.0    97.0         87.0      50.0    75.0
3      User 4       2       68.0    77.0         95.0     -99.0    61.0
4      User 5       2       98.0    54.0  Not present      95.0    86.0
..        ...     ...        ...     ...          ...       ...     ...
244  User 245      18      139.0   148.0        129.0     129.0   168.0
245  User 246      22      114.0   228.0        104.0      84.0   168.0
246  User 247      20      124.0   178.0        104.0     158.0   174.0
247  User 248      20      133.0   149.0        139.0     144.0   213.0
248  User 249      20      143.0   149.0        139.0     159.0   143.0

[249 rows x 7 columns]

Using interpolate() function to fill the missing values using linear method.

In [74]:
df.interpolate(method ='linear', limit_direction ='forward')

      User Id  Sports  Religious  Nature      Theatre  Shopping  Picnic
0      User 1       2       77.0    79.0         69.0      68.0    95.0
1      User 2       2       62.0    88.0  Not present      69.0    68.0
2      User 3       2       50.0    97.0         87.0      50.0    75.0
3      User 4       2       68.0    77.0         95.0      72.5    61.0
4      User 5       2       98.0    54.0  Not present      95.0    86.0
..        ...     ...        ...     ...          ...       ...     ...
244  User 245      18      139.0   148.0        129.0     129.0   168.0
245  User 246      22      114.0   228.0        104.0      84.0   168.0
246  User 247      20      124.0   178.0        104.0     158.0   174.0
247  User 248      20      133.0   149.0        139.0     144.0   213.0
248  User 249      20      143.0   149.0        139.0     159.0   143.0

[249 rows x 7 columns]

Dropping missing values using dropna()

Drop rows with at least one Nan value

In [75]:
df.dropna()

      User Id  Sports  Religious  Nature      Theatre  Shopping  Picnic
0      User 1       2       77.0    79.0         69.0      68.0    95.0
2      User 3       2       50.0    97.0         87.0      50.0    75.0
4      User 5       2       98.0    54.0  Not present      95.0    86.0
6      User 7       3       64.0    85.0         82.0      73.0    69.0
8      User 9       3       64.0   108.0         64.0      54.0    93.0
..        ...     ...        ...     ...          ...       ...     ...
244  User 245      18      139.0   148.0        129.0     129.0   168.0
245  User 246      22      114.0   228.0        104.0      84.0   168.0
246  User 247      20      124.0   178.0        104.0     158.0   174.0
247  User 248      20      133.0   149.0        139.0     144.0   213.0
248  User 249      20      143.0   149.0        139.0     159.0   143.0

[233 rows x 7 columns]

Dropping rows if all values in that row are missing.

In [76]:
df.dropna(how = 'all')

      User Id  Sports  Religious  Nature      Theatre  Shopping  Picnic
0      User 1       2       77.0    79.0         69.0      68.0    95.0
1      User 2       2       62.0     NaN  Not present      69.0    68.0
2      User 3       2       50.0    97.0         87.0      50.0    75.0
3      User 4       2       68.0    77.0         95.0       NaN    61.0
4      User 5       2       98.0    54.0  Not present      95.0    86.0
..        ...     ...        ...     ...          ...       ...     ...
244  User 245      18      139.0   148.0        129.0     129.0   168.0
245  User 246      22      114.0   228.0        104.0      84.0   168.0
246  User 247      20      124.0   178.0        104.0     158.0   174.0
247  User 248      20      133.0   149.0        139.0     144.0   213.0
248  User 249      20      143.0   149.0        139.0     159.0   143.0

[249 rows x 7 columns]

In [66]:
new_data = df.dropna(axis = 0, how ='any')
new_data

      User Id  Sports  Religious  Nature  Theatre  Shopping  Picnic
0      User 1       2       77.0    79.0     69.0      68.0    95.0
2      User 3       2       50.0    97.0     87.0      50.0    75.0
6      User 7       3       64.0    85.0     82.0      73.0    69.0
8      User 9       3       64.0   108.0     64.0      54.0    93.0
10    User 11       3      107.0    54.0     64.0     103.0    94.0
..        ...     ...        ...     ...      ...       ...     ...
244  User 245      18      139.0   148.0    129.0     129.0   168.0
245  User 246      22      114.0   228.0    104.0      84.0   168.0
246  User 247      20      124.0   178.0    104.0     158.0   174.0
247  User 248      20      133.0   149.0    139.0     144.0   213.0
248  User 249      20      143.0   149.0    139.0     159.0   143.0

[230 rows x 7 columns]

compare sizes of data frames so that we can come to know how many rows had at least 1 Null value

In [67]:
print("Old data frame length:", len(df))
print("New data frame length:", len(new_data))
print("Number of rows with at least 1 NA value: ", (len(df)-len(new_data)))

Old data frame length: 249
New data frame length: 230
Number of rows with at least 1 NA value:  19